---
- hosts: do
  become: sudo

  tasks:

  - name: install node
    apt: name={{item}} update_cache=yes state=latest
    with_items:
      - git
      - nodejs
      - npm

  - name: create var/www/html directory
    file: dest=/var/www/html/ state=directory owner=root group=root mode=0700

  - name: clone repository
    git: >
      dest=/var/www/html
      repo=https://github.com/kevingimbel/node-ansible-demo
      update=no
    sudo: yes
    sudo_user: root

  - name: Copy service file to /etc/systemd/system
    copy:
      src: ansible-node.service
      dest: /etc/systemd/system

  - name: install dependencies
    command: /usr/bin/npm install
    args:
      chdir: /var/www/html/

  - name: start ansible-node service
    systemd:
      daemon_reload: yes
      state: started
      name: ansible-node
      masked: no
      enabled: yes
